---
title: ""
---

## Project Description

This project seeks to understand how a change in climate patterns will affect seasonal, internal migration patterns in India and how can cities better support their transient work-force. Every year millions of workers in India migrate for a few months within the country looking for work. Increased uncertainty in weather patterns will increase uncertainty in agricultural labor demand and affect this migration pattern. This project will model the relationship between climate uncertainty and changes in migration patterns. It will also create a system map of entitlements available to this population and which entitlements are accessible to workers while they are on the move. This will help us understand the characteristics of this transient population and how can they be empowered to access their entitlements while migrating. 

## Bio  

Hardika Dayalani (HAR-dih-KAH duh-ya-la-NEE) is a doctoral candidate at the Pardee RAND Graduate School and an assistant policy researcher at RAND. She has an MPA from the University of Pennsylvania and a B.Tech in Ocean Engineering and Naval Architecture from IIT Kharagpur, India. Before joining Pardee RAND, Hardika worked with a nonprofit in India implementing post-displacement housing programs and researching sustainable building technologies. During her MPA, her research work focused on mapping change in neighborhoods in Philadelphia, PA. Her dissertation explores how populations on the move will navigate the climate emergency and cities of the future.